#ifndef CUSTOM_LIBC_INCLUDE_H
#define CUSTOM_LIBC_INCLUDE_H

typedef long unsigned int size_t;
typedef long unsigned int __uint64_t;
typedef long int __int64_t;
typedef int __builtin_va_list;
typedef int __gnuc_va_list;
typedef int va_list;
typedef signed char __int8_t;
typedef unsigned char __uint8_t;
typedef short int __int16_t;
typedef unsigned short int __uint16_t;
typedef int __int32_t;
typedef unsigned int __uint32_t;
typedef long int __int64_t;
typedef unsigned long int __uint64_t;
typedef long int __int_least64_t;
typedef unsigned long int __uint_least64_t;
typedef signed char __s8;
typedef unsigned char __u8;
typedef short int __s16;
typedef unsigned short int __u16;
typedef int __s32;
typedef unsigned int __u32;
typedef long int __s64;
typedef unsigned long int __u64;
typedef int _LOCK_T;
typedef int _LOCK_RECURSIVE_T;
typedef long int _off_t;
typedef int __dev_t;
typedef int __uid_t;
typedef int __gid_t;
typedef long int _off64_t;
typedef long int _fpos_t;
typedef int _ssize_t;
typedef unsigned int wint_t;
typedef int _mbstate_t;
typedef int _flock_t;
typedef int _iconv_t;
typedef unsigned long int __ULong;
typedef int __FILE;
typedef long int ptrdiff_t;
typedef int wchar_t;
typedef unsigned short int char16_t;
typedef unsigned int char32_t;
typedef long int __off_t;
typedef int __pid_t;
typedef long int __loff_t;
typedef unsigned char u_char;
typedef unsigned short int u_short;
typedef unsigned int u_int;
typedef unsigned long int u_long;
typedef unsigned short int ushort;
typedef unsigned int uint;
typedef long int clock_t;
typedef long int time_t;
typedef long int daddr_t;
typedef char * caddr_t;
typedef int ino_t;
typedef long int off_t;
typedef int dev_t;
typedef int uid_t;
typedef int gid_t;
typedef int pid_t;
typedef int key_t;
typedef int ssize_t;
typedef unsigned int mode_t;
typedef unsigned int nlink_t;
typedef unsigned long int fd_mask;
typedef int _types_fd_set;
typedef int clockid_t;
typedef int timer_t;
typedef unsigned int useconds_t;
typedef int suseconds_t;
typedef int FILE;
typedef long int fpos_t;
typedef int cookie_read_function_t;
typedef int cookie_write_function_t;
typedef int cookie_seek_function_t;
typedef int cookie_close_function_t;
typedef int cookie_io_functions_t;
typedef struct { int quot; int rem; } div_t;
typedef struct { long int quot; long int rem; } ldiv_t;
typedef struct { long long int quot; long long int rem; } lldiv_t;
typedef int sigset_t;
typedef int __sigset_t;
typedef void (*_sig_func_ptr)(int);
typedef int sig_atomic_t;
typedef struct { int __value[2]; } __tzrule_type;
typedef struct { int __value[4]; } __tzinfo_type;
typedef struct { int __value[2]; } mbstate_t;
typedef int sem_t;
typedef int pthread_t;
typedef int pthread_attr_t;
typedef int pthread_mutex_t;
typedef int pthread_mutexattr_t;
typedef int pthread_cond_t;
typedef int pthread_condattr_t;
typedef int pthread_key_t;
typedef int pthread_once_t;
typedef int pthread_rwlock_t;
typedef int pthread_rwlockattr_t;
typedef int pthread_spinlock_t;
typedef int pthread_barrier_t;
typedef int pthread_barrierattr_t;
typedef struct { int __jmpbuf[8]; } jmp_buf;
typedef int rlim_t;
typedef unsigned short int sa_family_t;
typedef struct { int __jmpbuf[8]; int __mask_was_saved; sigset_t __saved_mask; } sigjmp_buf;
typedef struct { void *ss_sp; int ss_flags; size_t ss_size; } stack_t;
typedef struct { int si_signo; int si_code; int si_errno; } siginfo_t;
typedef struct { void *next_in; unsigned int avail_in; unsigned long total_in; void *next_out; unsigned int avail_out; unsigned long total_out; char *msg; void *state; int zalloc; int zfree; void *opaque; int data_type; unsigned long adler; unsigned long reserved; } z_stream;
typedef signed char int8_t;
typedef unsigned char uint8_t;
typedef short int int16_t;
typedef unsigned short int uint16_t;
typedef int int32_t;
typedef unsigned int uint32_t;
typedef long int int64_t;
typedef unsigned long int uint64_t;
typedef signed char int_least8_t;
typedef unsigned char uint_least8_t;
typedef short int int_least16_t;
typedef unsigned short int uint_least16_t;
typedef int int_least32_t;
typedef unsigned int uint_least32_t;
typedef long int int_least64_t;
typedef unsigned long int uint_least64_t;
typedef signed char int_fast8_t;
typedef unsigned char uint_fast8_t;
typedef short int int_fast16_t;
typedef unsigned short int uint_fast16_t;
typedef int int_fast32_t;
typedef unsigned int uint_fast32_t;
typedef long int int_fast64_t;
typedef unsigned long int uint_fast64_t;
typedef long int intptr_t;
typedef unsigned long int uintptr_t;
typedef long int intmax_t;
typedef unsigned long int uintmax_t;
typedef int atomic_int;
typedef int UsingDeprecatedTrashcanMacro;

#endif // CUSTOM_LIBC_INCLUDE_H
